"""marketplace matching opportunities and lead connections
Revision ID: 034_marketplace_matching
Revises: 033_project_requests
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision="034_marketplace_matching";down_revision="033_project_requests";branch_labels=None;depends_on=None
def upgrade():
 ms=postgresql.ENUM("OPEN","COMPLETE",name="matching_run_status");os=postgresql.ENUM("OFFERED","ACCEPTED","DECLINED","EXPIRED",name="marketplace_opportunity_status");ms.create(op.get_bind(),checkfirst=True);os.create(op.get_bind(),checkfirst=True)
 op.create_table("matching_runs",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("project_request_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("project_requests.id",ondelete="CASCADE"),nullable=False),sa.Column("status",ms,nullable=False,server_default="OPEN"),sa.Column("version",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
 op.create_table("match_candidates",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("matching_run_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("matching_runs.id",ondelete="CASCADE"),nullable=False),sa.Column("vendor_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("vendors.id",ondelete="CASCADE"),nullable=False),sa.Column("score",sa.Integer(),nullable=False),sa.Column("reasons",postgresql.JSONB(),nullable=False),sa.Column("eligible",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("matching_run_id","vendor_id"))
 op.create_table("marketplace_opportunities",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("project_request_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("project_requests.id",ondelete="CASCADE"),nullable=False),sa.Column("vendor_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("vendors.id",ondelete="CASCADE"),nullable=False),sa.Column("status",os,nullable=False,server_default="OFFERED"),sa.Column("version",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("project_request_id","vendor_id"))
 op.create_table("lead_connections",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("project_request_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("project_requests.id",ondelete="CASCADE"),nullable=False),sa.Column("vendor_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("vendors.id",ondelete="CASCADE"),nullable=False),sa.Column("opportunity_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("marketplace_opportunities.id",ondelete="CASCADE"),nullable=False,unique=True),sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("project_request_id","vendor_id"))
def downgrade():
 op.drop_table("lead_connections");op.drop_table("marketplace_opportunities");op.drop_table("match_candidates");op.drop_table("matching_runs");postgresql.ENUM("OFFERED","ACCEPTED","DECLINED","EXPIRED",name="marketplace_opportunity_status").drop(op.get_bind(),checkfirst=True);postgresql.ENUM("OPEN","COMPLETE",name="matching_run_status").drop(op.get_bind(),checkfirst=True)
